model:
  seed: 0
  batch_size: 2
  optimizer: adam # sgd_mom, adam
  epochs: 80
  loss: dice # ce, dice, focal
  learning_rate: 0.001
  lr_decay_after_epoch: 40
  lr_decay_param: 0.1
  backbone: unet # unet, linknet
  encoder:
    backbone: resnet34 # densenet121, resnet34
    weights: imagenet # imagenet or None
  decoder:
    activation: softmax # softmax or None
  method: pionono # supervised, prob-unet, conf_matrix, pionono
  prob_unet_config:
    original_backbone: False # use original prob-unet backbone (overwrites above configuration of backbone)
    kl_factor: 1.0
    reg_factor: 0.00001
    latent_dim: 6
  pionono_config:
    mc_samples: 3
    no_head_layers: 4
    kl_factor: 0.01
    reg_factor: 0.00001
    latent_dim: 6
    z_prior_mu: 0.0
    z_prior_sigma: 2.0
    z_posterior_mu_rand_sigma: 4.0 # sigma of random initializer for posterior mean
    gold_annotator: 6
    z_learning_rate: 0.01
  conf_matrix_config:
    min_trace: False
    identity_reg: False
    alpha: 0.4

logging:
  interval: 10 # steps of train logging (in number of batches)
  artifact_interval: 1 # steps of artifact (e.g. visualization) logging (in number of epochs)
  mlruns_folder: /work/work_arne/mlflow_server # http://127.0.0.1:5002
  tags:
    stage: initial
    spec: default