data:
  dataset_config: dummy_experiment/dummy_dataset_config.yaml

model:
  epochs: 50
  batch_size: 2
  optimizer: sgd_mom # sgd_mom, adam
  learning_rate: 0.1
  lr_decay_after_epoch: 0
  lr_decay_param: 0.1
  backbone: unet # unet, linknet
  encoder:
    backbone: densenet121 # densenet121, resnet34
    weights: imagenet # imagenet or None
  decoder:
    activation: softmax # softmax or None

