data:
  class_no: 6
  class_weights: [44, 0.4756, 0.5844, 1.5684, 3.1598, 4.7606]
  path: ./dummy_experiment/data/
  train:
    images: patches
    masks: masks
  val:
    images: patches
    masks: masks
  test:
    images: patches
    masks: masks
  visualize_test_images: all #['core_A12F_AO_x_ini_0_y_ini_0.png', 'core_A12F_AO_x_ini_0_y_ini_358.png'] # set to 'all' if all images should be printed