data:
  dataset_name: dummy
  class_no: 5
  class_weights: [1,1,1,1,1] #[0.4756, 0.5844, 1.5684, 3.1598, 4.7606]
  ignore_last_class: True # index of class in gt to be deleted, else 'None'
  path: ./dummy_experiment/data/
  train:
    images: patches
    masks: masks
  val:
    images: patches
    masks: masks
  test:
    images: patches
    masks: masks
  visualize_images:
    val: ['core_A1EW_BH_x_ini_3580_y_ini_2864.png', 'core_A6SB_EW_x_ini_1074_y_ini_2864.png'] # 'all', 'None' or ['img1', 'img2'..]
    test: all #['core_A12F_AO_x_ini_0_y_ini_0.png', 'core_A12F_AO_x_ini_0_y_ini_358.png'] # 'all', 'None' or ['img1', 'img2'..]
  augmentation:
    use_augmentation: False # automatically flips and 90 degree rotations are used in this case
    gaussian_blur_kernel: 3 # range 3-7
    brightness_limit: 0.2
    contrast_limit: 0.2
    hue_shift_limit: 20
    sat_shift_limit: 30



