data:
  dataset_name: gleason19_crowdsourcing
  crowd: True
  sr_experiment: False
  class_no: 5
  class_names: ['NC', 'GG3', 'GG4', 'GG5', 'other']
  class_weights: [1., 1., 1., 1., 1.]
  ignore_last_class: False # set True if last class will be ignored during training and testing
  ignore_last_class_only_for_testing: True # set True if last class will be ignored during  testing
  path: /home/arne/data/Gleason_2019/resized_dataset_1024/
  train:
    images: Crossval2/train
    masks:
      - Maps/STAPLE
      - Maps/Maps1_T
      - Maps/Maps2_T
      - Maps/Maps3_T
      - Maps/Maps4_T
      - Maps/Maps5_T
      - Maps/Maps6_T
  val:
    images: Crossval2/val
    masks:
      - Maps/STAPLE
      - Maps/Maps1_T
      - Maps/Maps2_T
      - Maps/Maps3_T
      - Maps/Maps4_T
      - Maps/Maps5_T
      - Maps/Maps6_T
  test:
    images: Crossval2/val
    masks:
      - Maps/STAPLE
      - Maps/Maps1_T
      - Maps/Maps2_T
      - Maps/Maps3_T
      - Maps/Maps4_T
      - Maps/Maps5_T
      - Maps/Maps6_T
  visualize_images:
    train:
      - 'slide001_core005.png'
      - 'slide001_core011.png'
      - 'slide001_core146.png'
      - 'slide001_core156.png'
      - 'slide002_core033.png'
      - 'slide002_core050.png'
      - 'slide002_core072.png'
      - 'slide005_core075.png'
      - 'slide005_core104.png'
      - 'slide007_core146.png'
    val:
      - 'slide001_core003.png'
      - 'slide001_core077.png'
      - 'slide001_core160.png'
      - 'slide002_core025.png'
      - 'slide005_core051.png'
      - 'slide005_core058.png'
      - 'slide005_core104.png'
      - 'slide006_core019.png'
      - 'slide006_core047.png'
      - 'slide007_core005.png'
      - 'slide007_core149.png'
    test:
      - 'slide001_core003.png'
      - 'slide001_core077.png'
      - 'slide001_core160.png'
      - 'slide002_core025.png'
      - 'slide005_core051.png'
      - 'slide005_core058.png'
      - 'slide005_core104.png'
      - 'slide006_core019.png'
      - 'slide006_core047.png'
      - 'slide007_core005.png'
      - 'slide007_core149.png'
  normalization: False
  augmentation:
    use_augmentation: True # switch everything off and on, if True automatically flips and 90 degree rotations are used in this case
    gaussian_blur_kernel: 5 # range 3-7
    brightness_limit: 0.2
    contrast_limit: 0.2
    hue_shift_limit: 20
    sat_shift_limit: 30



